<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <UseWPF>True</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToastNotifications\ToastNotifications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="toast-notifications-icon.ico" />
  </ItemGroup>

</Project>
