<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <!-- 指定所有目标框架 -->
	  <TargetFrameworks>net40-windows;net462-windows;net472-windows;net481-windows;net6.0-windows;net8.0-windows</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>toast-notifications-icon.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup Condition="('$(Configuration)' == 'Release') And ('$(UseTemporarySignCert)' != 'true')">
    <AssemblyOriginatorKeyFile>../../Build/DevCrew.ToastNotifications.pfx</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup Condition="('$(Configuration)' == 'Debug') Or ('$(UseTemporarySignCert)' == 'true')">
    <AssemblyOriginatorKeyFile>../../Build/DevCrew.ToastNotifications_TemporaryKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="DevCrew.ToastNotifications.pfx" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ToastNotifications\ToastNotifications.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="toast-notifications-icon.ico" />
  </ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' != 'net40-windows'">
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
	</ItemGroup>
</Project>